mkdocs/charts/argo/argo.md, mkdocs/index.md, mkdocs/infra/azure/azure.md
=> update index and azure.md

charts/utils/kgst-0.1.0/Chart.yaml, charts/utils/kgst-0.1.0/templates/helm-repository.yaml, charts/utils/kgst-0.1.0/templates/service-template.yaml, charts/utils/kgst-0.1.0/values.yaml
=> Add k0rdent generic service template helm chart

charts/utils/kgst-0.1.0/templates/service-template.yaml, charts/utils/kgst-0.1.0/values.yaml
=> Add optional "prefix" value to kgst

charts/utils/kgst-0.1.0/templates/service-template.yaml
=> Use service-template-1-2-3 to keep consistency

mkdocs/charts/kdash/kdash.md, mkdocs/charts/kubecost/kubecost.md, mkdocs/charts/open-webui/open-webui.md
=> Fix service template names in docs

charts/utils/kgst-0.1.0/templates/helm-repository.yaml, charts/utils/kgst-0.1.0/templates/service-template.yaml
=> Add helm keep annotation to kgst helm-repository and service-template

mkdocs/charts/msr/msr.md, mkdocs/charts/msr/msr_logo.svg, paths.json
This commit adds the current MSR4 helm chart to the application catalog
=> Add MSR4 to catalog

charts/utils/kgst-0.1.0/templates/NOTES.txt
=> Update kgst chart

charts/utils/aws-credential/Chart.yaml, charts/utils/aws-credential/templates/NOTES.txt, charts/utils/aws-credential/templates/aws-cluster-identity.yaml, charts/utils/aws-credential/templates/credential.yaml, charts/utils/aws-credential/templates/resource-template.yaml, charts/utils/aws-credential/templates/secret.yaml, charts/utils/aws-credential/values.yaml
=> Add "aws-credential" helm chart

mkdocs/CNAME
=> Add CNAME to mkdocs

mkdocs/charts/argo/argo.md, mkdocs/charts/calico/calico.md, mkdocs/charts/cert-manager/cert-manager.md, mkdocs/charts/dapr/dapr.md, mkdocs/charts/dex/dex.md, mkdocs/charts/external-dns/external-dns.md, mkdocs/charts/external-secrets/external-secrets.md, mkdocs/charts/ingress-nginx/ingress-nginx.md, mkdocs/charts/istio/istio.md, mkdocs/charts/kdash/kdash.md, mkdocs/charts/kubecost/kubecost.md, mkdocs/charts/kyverno/kyverno.md, mkdocs/charts/msr/msr.md, mkdocs/charts/netapp/netapp.md, mkdocs/charts/nvidia/nvidia.md, mkdocs/charts/open-webui/open-webui.md, mkdocs/charts/pure/pure.md, mkdocs/charts/velero/velero.md, mkdocs/infra/aws/aws.md, mkdocs/infra/azure/azure.md, mkdocs/infra/openstack/openstack.md, mkdocs/infra/vsphere/vsphere.md
=> Add "Prerequisites" section to install steps

mkdocs/infra/aws/aws.md, mkdocs/infra/azure/azure.md, mkdocs/infra/openstack/openstack.md, mkdocs/infra/vsphere/vsphere.md
=> Fix infra docs titles

.gitignore, examples/README.md, examples/kubecost/cld.yaml, examples/kubecost/helm-values-kgst.yaml, examples/kubecost/mcs-aws.yaml, examples/open-webui/cld.yaml, examples/open-webui/helm-values-kgst.yaml, examples/open-webui/mcs-aws.yaml, examples/opencost/cld.yaml, examples/opencost/helm-values-kgst.yaml, examples/opencost/mcs-aws.yaml, examples/providers/values-aws-credential.yaml, examples/scripts/set_envs_template.sh, examples/scripts/test_webpage.sh, examples/scripts/wait_for_cluster.sh, examples/scripts/wait_for_cluster_removal.sh, examples/scripts/wait_for_deployment.sh, examples/scripts/wait_for_deployment_removal.sh
=> Add examples folder with universal testing workflow

mkdocs/charts/open-webui/open-webui.md
=> open-webui: add gif video

examples/README.md, examples/external-dns/cld.yaml, examples/external-dns/helm-values-kgst.yaml, examples/external-dns/mcs-aws.yaml
=> external-dns: verify in AWS

examples/README.md, examples/argo-cd/cld.yaml, examples/argo-cd/helm-values-kgst.yaml, examples/argo-cd/mcs-aws.yaml, examples/dapr/cld.yaml, examples/dapr/helm-values-kgst.yaml, examples/dapr/mcs-aws.yaml, examples/kubernetes-dashboard/cld.yaml, examples/kubernetes-dashboard/helm-values-kgst.yaml, examples/kubernetes-dashboard/mcs-aws.yaml, examples/scripts/test_webpage.sh, mkdocs/charts/argo/argo.md, mkdocs/charts/dapr/dapr.md
=> Verify services

mkdocs/contribute.md
=> Add "contribute" page

examples/README.md, examples/prometheus/cld.yaml, examples/prometheus/helm-values-kgst.yaml, examples/prometheus/mcs-aws.yaml, examples/scripts/test_webpage.sh, mkdocs/apps/prometheus/data.yaml
=> Add Prometheus app

charts/utils/adopted-credential/Chart.yaml, charts/utils/adopted-credential/templates/NOTES.txt, charts/utils/adopted-credential/templates/credential.yaml, charts/utils/adopted-credential/templates/resource-template.yaml, charts/utils/adopted-credential/templates/secret.yaml, charts/utils/adopted-credential/values.yaml
=> Add "adopted-credential" chart

charts/utils/azure-credential/Chart.yaml, charts/utils/azure-credential/templates/NOTES.txt, charts/utils/azure-credential/templates/azure-cluster-identity.yaml, charts/utils/azure-credential/templates/credential.yaml, charts/utils/azure-credential/templates/resource-template.yaml, charts/utils/azure-credential/templates/secret.yaml, charts/utils/azure-credential/values.yaml, examples/scripts/set_envs_template.sh
=> Add "azure-credential" helm chart

examples/README.md, examples/argo-cd/mcs.yaml, examples/aws.md, examples/cert-manager/mcs.yaml, examples/dapr/mcs.yaml, examples/dex/mcs.yaml, examples/external-dns/mcs.yaml, examples/external-secrets/mcs.yaml, examples/ingress-nginx/mcs.yaml, examples/kubecost/mcs.yaml, examples/kubernetes-dashboard/mcs.yaml, examples/kyverno/mcs.yaml, examples/local.md, examples/open-webui/mcs.yaml, examples/opencost/mcs.yaml, examples/prometheus/mcs.yaml, examples/providers/adopted-cld.yaml, examples/providers/kind-adopted-cluster.yaml, examples/scripts/test_webpage.sh, examples/velero/mcs.yaml
=> Add local testing workflow

.github/workflows/helm-app-deploy.yml, .gitignore, apps/dapr/example/Chart.yaml, apps/dapr/example/values.yaml, docs/testing.md, mkdocs/contribute.md, providers/adopted-cld.yaml, scripts/deploy_cld.sh, scripts/deploy_example_chart.sh, scripts/deploy_k0rdent.sh, scripts/deploy_mcs.sh, scripts/example_chart_exists.sh, scripts/install_svc_tpl.sh, scripts/remove_cld.sh, scripts/remove_mcs.sh, scripts/setup_provider_credential.sh, scripts/show_install_cmd.py, scripts/test_webpage.sh, scripts/uninstall_example_chart.sh, scripts/wait_for_cld.sh, scripts/wait_for_cluster_removal.sh, scripts/wait_for_deployment.sh, scripts/wait_for_deployment_removal.sh
=> Add github action test for added application

.github/workflows/helm-app-deploy.yml, apps/dapr/example/Chart.yaml
=> Add github actions job "test-service-template"

mkdocs/apps/app.tpl.md, mkdocs/apps/aws/data.yaml, mkdocs/apps/azure/data.yaml, mkdocs/apps/calico/data.yaml, mkdocs/apps/cert-manager/data.yaml, mkdocs/apps/dapr/data.yaml, mkdocs/apps/dex/data.yaml, mkdocs/apps/external-dns/data.yaml, mkdocs/apps/external-secrets/data.yaml, mkdocs/apps/ingress-nginx/data.yaml, mkdocs/apps/istio/data.yaml, mkdocs/apps/kube-prometheus-stack/data.yaml, mkdocs/apps/kubernetes-dashboard/data.yaml, mkdocs/apps/kyverno/data.yaml, mkdocs/apps/netapp/data.yaml, mkdocs/apps/nvidia/data.yaml, mkdocs/apps/open-webui/data.yaml, mkdocs/apps/opencost/data.yaml, mkdocs/apps/openstack/data.yaml, mkdocs/apps/prometheus/data.yaml, mkdocs/apps/pure/data.yaml, mkdocs/apps/velero/data.yaml, mkdocs/apps/vsphere/data.yaml, mkdocs/gen_app_pages.py
=> Add tags validation to "gen_app_pages.py" script, reduce tags list

apps/istio/example/Chart.yaml, docs/testing.md, mkdocs/apps/istio/data.yaml, mkdocs/gen_app_pages.py, scripts/deploy_example_chart.sh, scripts/deploy_k0rdent.sh, scripts/deploy_mcs.sh, scripts/get_mcs_namespace.sh, scripts/remove_k0rdent.sh, scripts/remove_mcs.sh, scripts/uninstall_example_chart.sh, scripts/utils.py, scripts/wait_for_cld.sh
=> Updated scritps, verify istio

apps/open-webui/aws-cld.yaml, apps/open-webui/example/Chart.yaml, apps/open-webui/example/values.yaml, scripts/deploy_cld.sh
=> Use optional app specific aws-cld.yaml or default one

apps/netapp/example/Chart.yaml
=> Add NetApp testing chart

.github/workflows/helm-app-deploy.yml, apps/nvidia/example/Chart.yaml, docs/testing.md
=> Add nvidia gpu operator testing chart

apps/msr/assets/msr_logo.svg, apps/msr/data.yaml, apps/msr/example/Chart.yaml, apps/msr/example/values.yaml, docs/testing.md, scripts/utils.py
=> Add msr app again

apps/calico/data.yaml, mkdocs/app.tpl.md
=> Updating calico (operator to CNI)

apps/external-dns/mcs.yaml, apps/open-webui/aws-cld.yaml, providers/aws-cld.yaml, providers/azure-cld.yaml, providers/values-aws-credential.yaml, scripts/deploy_cld.sh, scripts/set_envs_template.sh, scripts/setup_provider_credential.sh
=> Add TEST_MODE=azure support

apps/dapr/example/values.yaml, apps/kubecost/example/values.yaml, apps/kubernetes-dashboard/mcs.yaml, apps/msr/example/values.yaml, apps/open-webui/example/values.yaml, apps/opencost/example/values.yaml, apps/prometheus/example/values.yaml
=> Add ingress-nginx azure annotation fix

README.md
=> Describe repo structure

apps/dapr/data.yaml, apps/kubecost/data.yaml, apps/kubernetes-dashboard/data.yaml, apps/msr/data.yaml, apps/open-webui/data.yaml, apps/opencost/data.yaml, apps/prometheus/data.yaml, mkdocs/app.tpl.md, mkdocs/gen_app_pages.py
=> Add ingress-nginx requirement for apps with frontend

apps/ingress-nginx/data.yaml, apps/ingress-nginx/example/Chart.yaml, apps/ingress-nginx/example/values.yaml
- kubernetes/kubernetes#131009
- CVE-2025-1974
=> ingress-nginx: update disclaimer

apps/nvidia/aws-cld.yaml, apps/nvidia/azure-cld.yaml, apps/nvidia/data.yaml, apps/nvidia/example/values.yaml, apps/open-webui/data.yaml, apps/open-webui/mcs-gpu.yaml
=> open-webui: support GPU config

apps/gatekeeper/data.yaml, apps/node-feature-discovery/data.yaml, docs/testing.md, mkdocs/gen_app_pages.py
=> Fixes and updates

mkdocs/index.md
This reverts commit e68a40fd1b2833472fa5716fb58f6229ddf286b7.
=> revert "Switch to vuejs" - bug in mobile view

docs/testing.md, scripts/config/adopted-cld.yaml, scripts/config/aws-cld.yaml, scripts/config/azure-cld.yaml, scripts/deploy_k0rdent.sh, scripts/wait_for_cld.sh
This reverts commit edbd8f6e7d35efb79eb8183dfbaa8989c1f71f45.
=> Revert testing to k0rdent 0.1.0

apps/cert-manager/data.yaml
Inline guide/hint for those wanting to enable cert-manager CRDs.
=> docs: surface how to enable cert-manager CRDs

apps/gcp/assets/gce_logo.svg, apps/gcp/data.yaml, apps/gke/assets/gke_logo.svg, apps/gke/data.yaml
=> Add Google Cloud infra

apps/cadvisor/data.yaml, apps/gatekeeper/data.yaml, apps/kube-prometheus-stack/data.yaml, apps/metallb/data.yaml, apps/minio/data.yaml, mkdocs/gen_app_pages.py
... as @lxie123 mentioned some app summaries are too long and it doesn't look nice. So adjusting and adding validation rule
=> Add "summary chars limit"

mkdocs/CNAME, scripts/deploy_web.sh
=> Fix custom domain setting adding CNAME to gh-pages branch

charts/providers/cluster-api-provider-kubevirt/Chart.yaml, charts/providers/cluster-api-provider-kubevirt/templates/provider.yaml, charts/providers/cluster-api-provider-kubevirt/templates/secret.yaml, charts/providers/cluster-api-provider-kubevirt/values.schema.json, charts/providers/cluster-api-provider-kubevirt/values.yaml, charts/providers/kubevirt-standalone-cp/Chart.yaml, charts/providers/kubevirt-standalone-cp/templates/_helpers.tpl, charts/providers/kubevirt-standalone-cp/templates/cluster.yaml, charts/providers/kubevirt-standalone-cp/templates/k0scontrolplane.yaml, charts/providers/kubevirt-standalone-cp/templates/k0sworkerconfigtemplate.yaml, charts/providers/kubevirt-standalone-cp/templates/kubevirtcluster.yaml, charts/providers/kubevirt-standalone-cp/templates/kubevirtmachinetemplate-controlplane.yaml, charts/providers/kubevirt-standalone-cp/templates/kubevirtmachinetemplate-worker.yaml, charts/providers/kubevirt-standalone-cp/templates/machinedeployment.yaml, charts/providers/kubevirt-standalone-cp/values.schema.json, charts/providers/kubevirt-standalone-cp/values.yaml
Demo: https://github.com/s3rj1k/k0rdent-kcm-oot
=> Add `KubeVirt` provider charts

.github/workflows/helm-chart-build.yml, mkdocs/gen_app_pages.py
- Build single changed charts
- Skip apps without data.yaml in web build
=> Update CI scripts

.github/workflows/helm-chart-build.yml, apps/argo-cd/charts/argo-cd-7.8.0/Chart.lock, apps/argo-cd/charts/argo-cd-7.8.0/Chart.yaml, apps/argo-cd/charts/argo-cd-service-template-7.8.0/Chart.lock, apps/argo-cd/charts/argo-cd-service-template-7.8.0/Chart.yaml, apps/argo-cd/charts/argo-cd-service-template-7.8.0/templates/service-template.yaml
=> Add argo-cd charts

apps/arangodb/example/Chart.yaml, apps/argo-cd/example/Chart.yaml, apps/clearml/example/Chart.yaml, apps/clearml/example/values.yaml
=> Update app tests

apps/dapr/example/Chart.yaml, apps/dapr/example/values.yaml, apps/envoy-gateway/example/Chart.yaml
=> Update apps tests (dapr, ...)

apps/istio/example/Chart.yaml
=> Update istio example

apps/nvidia/example/Chart.yaml, apps/nvidia/example/values.yaml
=> gpu-operator: update test

.github/workflows/helm-app-deploy.yml, .github/workflows/reusable-build.yml, apps/open-webui/charts/open-webui-5.13.0/Chart.lock, apps/open-webui/charts/open-webui-5.20.0/Chart.lock, apps/open-webui/charts/open-webui-5.20.0/Chart.yaml, apps/open-webui/charts/open-webui-service-template-5.20.0/Chart.lock, apps/open-webui/charts/open-webui-service-template-5.20.0/Chart.yaml, apps/open-webui/charts/open-webui-service-template-5.20.0/templates/service-template.yaml, apps/open-webui/charts/st-charts.yaml
=> open-webui: use version 5.20.0

apps/open-webui/example/Chart.yaml, apps/open-webui/example/values.yaml
=> open-webui: update test to reference catalog ghcr registry

apps/mysql/example/Chart.yaml, apps/netapp/example/Chart.yaml, apps/node-feature-discovery/example/Chart.yaml, apps/opencost/example/Chart.yaml, apps/opencost/example/values.yaml, apps/postgresql/example/Chart.yaml, apps/prometheus/example/Chart.yaml, apps/prometheus/example/values.yaml
=> Update tests (mysql-operator, ...)

apps/kubevirt/charts/kubevirt-0.1.0/Chart.yaml, apps/kubevirt/charts/kubevirt-0.1.0/crds/kubevirt.yaml, apps/kubevirt/charts/kubevirt-0.1.0/templates/cluster-role-bindings.yaml, apps/kubevirt/charts/kubevirt-0.1.0/templates/cluster-roles.yaml, apps/kubevirt/charts/kubevirt-0.1.0/templates/deployments.yaml, apps/kubevirt/charts/kubevirt-0.1.0/templates/kubevirts.yaml, apps/kubevirt/charts/kubevirt-0.1.0/templates/namespaces.yaml, apps/kubevirt/charts/kubevirt-0.1.0/templates/priority-classes.yaml, apps/kubevirt/charts/kubevirt-0.1.0/templates/role-bindings.yaml, apps/kubevirt/charts/kubevirt-0.1.0/templates/roles.yaml, apps/kubevirt/charts/kubevirt-0.1.0/templates/service-accounts.yaml, apps/kubevirt/charts/kubevirt-0.1.0/values.schema.json, apps/kubevirt/charts/kubevirt-0.1.0/values.yaml
dependency for https://github.com/k0rdent/catalog/pull/314
=> Add `KubeVirt` chart

scripts/wait_for_deployment.sh
- Added diagnostic output for better understanding of pod statuses
- Suggested using `json` output from kubectl for more reliable parsing
- Included fallback message when timeout is reached to aid debugging
=> Improve pod readiness check script with timeout handling and error diagnostics

apps/msr/charts/harbor-4.0.1/Chart.lock, apps/msr/charts/harbor-4.0.1/Chart.yaml, apps/msr/charts/harbor-service-template-4.0.1/Chart.lock, apps/msr/charts/harbor-service-template-4.0.1/Chart.yaml, apps/msr/charts/harbor-service-template-4.0.1/templates/service-template.yaml, apps/msr/charts/st-charts.yaml
=> msr harbor: add charts

.github/workflows/helm-app-deploy.yml
- use fork registry in pull_request tests and fork push tests
- use fork registry only when app charts were changed
=> Update helm-app-deploy.yml script

scripts/wait_for_cld.sh, scripts/wait_for_cluster_removal.sh, scripts/wait_for_deployment.sh, scripts/wait_for_deployment_removal.sh, scripts/wait_for_servicetemplate.sh
- wait_for_deployment.sh: show "kubectl get pod" output
- use icon chars for success and waiting states
=> Improve wait_for_*.sh scripts output

apps/nirmata/data.yaml, mkdocs/app.tpl.md, mkdocs/gen_app_pages.py
- install from k0rdent-enterprise repo
=> nirmata: Add nirmata-kyverno install instruction

apps/gcp/data.yaml, apps/gke/data.yaml, apps/kubevirt/data.yaml, mkdocs/gen_app_pages.py, scripts/deploy_web.sh, scripts/utils.py
Demo: https://josca.github.io/k0rdent-catalog-3/
=> Add k0rdent 0.3.0 support

apps/kyverno-guardrails/data.yaml, apps/kyverno-guardrails/docs/README.md
This PR contains description of how to customize provided policies.
Fixes: #k0rdent/kcm#1308
=> docs: kyverno-guardrails how-to guide

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/epic.md, .github/ISSUE_TEMPLATE/feature-request.md
=> Add issue templates

apps/istio-ambient/charts/istio-cni-1.24.3/Chart.lock, apps/istio-ambient/charts/istio-cni-1.24.3/Chart.yaml, apps/istio-ambient/charts/istio-cni-service-template-1.24.3/Chart.lock, apps/istio-ambient/charts/istio-cni-service-template-1.24.3/Chart.yaml, apps/istio-ambient/charts/istio-cni-service-template-1.24.3/templates/service-template.yaml, apps/istio-ambient/charts/istio-ztunnel-1.24.3/Chart.lock, apps/istio-ambient/charts/istio-ztunnel-1.24.3/Chart.yaml, apps/istio-ambient/charts/istio-ztunnel-service-template-1.24.3/Chart.lock, apps/istio-ambient/charts/istio-ztunnel-service-template-1.24.3/Chart.yaml, apps/istio-ambient/charts/istio-ztunnel-service-template-1.24.3/templates/service-template.yaml, apps/istio-ambient/charts/st-charts.yaml, apps/istio-ambient/data.yaml, apps/istio-ambient/example/Chart.yaml, apps/istio-ambient/example/values.yaml, hunspell_dict.txt
[Demo](https://josca.github.io/k0rdent-catalog-4/latest/apps/istio-ambient/)
=> Add istio-ambient

apps/aks/data.yaml, apps/amd-gpu/data.yaml, apps/aws/data.yaml, apps/azure/data.yaml, apps/eks/data.yaml, apps/gcp/data.yaml, apps/gitlab/data.yaml, apps/gke/data.yaml, apps/nvidia/data.yaml, apps/open-webui/data.yaml, apps/openstack/data.yaml, apps/vsphere/data.yaml, mkdocs/gen_app_pages.py
- k0rdent/catalog#421
- as cluster templates dash version are different from k0rdent version since v0.3.0
=> Fix clustertemplate versions in docs

apps/argo-cd/data.yaml, apps/argo-cd/example/Chart.yaml, apps/argo-cd/example/values.yaml, hunspell_dict.txt, mkdocs/app.tpl.md, mkdocs/gen_app_pages.py
[Demo: Josca/k0rdent-catalog-3](https://josca.github.io/k0rdent-catalog-3/latest/apps/argo-cd/#examples)
=> Argo example, add optional Examples tab

mkdocs/gen_app_pages.py, scripts/deploy_web.sh
Demo: https://josca.github.io/k0rdent-catalog-2/latest/
=> Add v1.0.0 support

README.md, docs/testing_methodology.md
Demo: https://github.com/Josca/k0rdent-catalog/blob/test-meth/docs/testing_methodology.md
=> Add "Testing Methodology" doc page.

mkdocs/app.tpl.md
This reverts commit d04e75a4c80ba607128b868a5e2fa5e7e0ef7a6b.
=> Revert metadata head to app.tpl.md

mkdocs/gen_app_pages.py, scripts/deploy_mcs.sh, scripts/utils.py, scripts/wait_for_deployment.sh
- do not require Ready state for running pods, just wait for running pods
=> Add "test_wait_for_running" test option

apps/kyverno/charts/kyverno-3.5.2/Chart.lock, apps/kyverno/charts/kyverno-3.5.2/Chart.yaml, apps/kyverno/charts/st-charts.yaml, apps/kyverno/data.yaml, apps/kyverno/example/Chart.yaml
- fixed updating to kyverno 3.5.2
=> kyverno: fix bitnami dependency issue (kubectl image)
